import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="forest">
      <body>
      <nav className="bg-neutral p-5 fixed w-full">
        <Link href={"/"} className="block w-full text-center text-xl text-white">
          Quiz AI
        </Link>
      </nav>
      {children}
      </body>
    </html>
  )
}
